# -*- coding: utf-8 -*-
"""CATT-Net: Correlation-Aware Tiny Transformer Network.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1j9P0rVFgTas-mTxX7OKWwWH0Oe58ynAG
"""

!pip install numpy pandas tensorflow matplotlib scikit-learn

import os
import json
import random
import warnings
from typing import Callable, Dict, List, Optional, Tuple

import numpy as np
import pandas as pd
import tensorflow as tf
import matplotlib.pyplot as plt

from sklearn.preprocessing import MinMaxScaler
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from sklearn.linear_model import LinearRegression
from sklearn.multioutput import MultiOutputRegressor
from tensorflow.keras import layers, Model

warnings.filterwarnings("ignore")

# =========================================================
# CONFIG
# =========================================================
SEED = 42
random.seed(SEED)
np.random.seed(SEED)
tf.random.set_seed(SEED)

#CSV_PATH = r"/content/Raw_data_1Hr_2024_site_5111_Jadavpur_Kolkata_WBPCB_1Hr.csv"
#CSV_PATH = r"/content/Raw_data_1Hr_2024_Delhi_1Hr.csv"
CSV_PATH = r"/content/Raw_data_1Hr_2024_site_1406_Secretariat_Amaravati_APPCB_1Hr (1) (1).csv"
OUT_DIR = "corrgan_tiny_transformer_ablation_baselines_int8_v2"
os.makedirs(OUT_DIR, exist_ok=True)

TIMESTAMP_COL = "Timestamp"
POLLUTANT_INPUT_COLS = ["PM2.5", "NO", "NO2", "Nox", "NH3", "SO2", "CO", "Ozone"]
TARGET_COLS = ["PM2.5", "NO2", "Ozone", "SO2"]
TIME_FEATURES = [
    "hour_sin", "hour_cos",
    "dow_sin", "dow_cos",
    "month_sin", "month_cos",
]
INPUT_FEATURES = POLLUTANT_INPUT_COLS + TIME_FEATURES

MISSING_SENTINEL = -1.0

FORECAST_SEQ_LEN = 12
TARGET_HORIZON = 1
TRAIN_RATIO = 0.70
VAL_RATIO = 0.15

BATCH_SIZE = 16
MODEL_EPOCHS = 120
BASELINE_EPOCHS = 60
ABLATION_EPOCHS = 45
LEARNING_RATE = 2e-4

CORRGAN_EPOCHS = 100
CORRGAN_BATCH_SIZE = 64
CORRGAN_LATENT_DIM = 32
CORRGAN_POOL_SIZE = 4000
CORRGAN_TOPK = 20
CORR_LAMBDA = 5.0

CLIP_LOWER_Q = 0.01
CLIP_UPPER_Q = 0.99

D_MODEL = 48
NUM_HEADS = 4
FF_DIM = 128
TRANSFORMER_DROPOUT = 0.10
NUM_TRANSFORMER_BLOCKS = 3
CONV_FILTERS = 48
HEAD_DENSE_1 = 96
HEAD_DENSE_2 = 48


# =========================================================
# UTILS
# =========================================================
def set_global_determinism(seed: int = 42) -> None:
    random.seed(seed)
    np.random.seed(seed)
    tf.random.set_seed(seed)


# =========================================================
# DATA LOADING
# =========================================================
def load_data(path: str) -> pd.DataFrame:
    if not os.path.exists(path):
        raise FileNotFoundError(f"CSV file not found: {path}")

    df = pd.read_csv(path)
    if TIMESTAMP_COL not in df.columns:
        raise ValueError(f"Timestamp column '{TIMESTAMP_COL}' not found in CSV.")

    df[TIMESTAMP_COL] = pd.to_datetime(df[TIMESTAMP_COL], errors="coerce")
    df = df.dropna(subset=[TIMESTAMP_COL]).sort_values(TIMESTAMP_COL).reset_index(drop=True)
    return df

def validate_required_columns(df: pd.DataFrame) -> None:
    required_cols = [TIMESTAMP_COL] + POLLUTANT_INPUT_COLS
    missing_cols = [c for c in required_cols if c not in df.columns]
    if missing_cols:
        raise ValueError(f"Missing required columns in CSV: {missing_cols}")

# =========================================================
# FEATURE ENGINEERING
# =========================================================
def add_time_features(df: pd.DataFrame) -> pd.DataFrame:
    df = df.copy()
    ts = pd.to_datetime(df[TIMESTAMP_COL], errors="coerce")

    hour = ts.dt.hour.fillna(0).astype(int)
    dow = ts.dt.dayofweek.fillna(0).astype(int)
    month = ts.dt.month.fillna(1).astype(int)

    df["hour_sin"] = np.sin(2 * np.pi * hour / 24.0)
    df["hour_cos"] = np.cos(2 * np.pi * hour / 24.0)
    df["dow_sin"] = np.sin(2 * np.pi * dow / 7.0)
    df["dow_cos"] = np.cos(2 * np.pi * dow / 7.0)
    df["month_sin"] = np.sin(2 * np.pi * (month - 1) / 12.0)
    df["month_cos"] = np.cos(2 * np.pi * (month - 1) / 12.0)
    return df

def clip_outliers(df: pd.DataFrame, cols: List[str], lower_q: float = 0.01, upper_q: float = 0.99) -> pd.DataFrame:
    df = df.copy()
    for col in cols:
        lo = df[col].quantile(lower_q)
        hi = df[col].quantile(upper_q)
        df[col] = df[col].clip(lo, hi)
    return df

# =========================================================
# CORRGAN-STYLE IMPUTATION
# =========================================================
def coarse_fill_matrix(X_missing: np.ndarray, feature_names: List[str], sentinel: float = -1.0) -> np.ndarray:
    df = pd.DataFrame(X_missing.copy(), columns=feature_names)
    pollutant_subset = [c for c in POLLUTANT_INPUT_COLS if c in df.columns]
    if pollutant_subset:
        df[pollutant_subset] = df[pollutant_subset].replace(sentinel, np.nan)
        df[pollutant_subset] = df[pollutant_subset].interpolate(limit_direction="both").ffill().bfill().fillna(0.0)
    return df.values.astype(np.float32)


def batch_corr(x: tf.Tensor) -> tf.Tensor:
    x_center = x - tf.reduce_mean(x, axis=0, keepdims=True)
    cov = tf.matmul(x_center, x_center, transpose_a=True) / (tf.cast(tf.shape(x)[0], tf.float32) - 1.0 + 1e-8)
    std = tf.sqrt(tf.maximum(tf.linalg.diag_part(cov), 1e-8))
    denom = tf.tensordot(std, std, axes=0) + 1e-8
    return cov / denom


def build_generator(latent_dim: int, output_dim: int, hidden_dim: int = 128) -> Model:
    z = layers.Input(shape=(latent_dim,))
    x = layers.Dense(hidden_dim, activation="relu")(z)
    x = layers.Dense(hidden_dim, activation="relu")(x)
    out = layers.Dense(output_dim, activation="sigmoid")(x)
    return Model(z, out, name="generator")


def build_discriminator(input_dim: int, hidden_dim: int = 128) -> Model:
    x_in = layers.Input(shape=(input_dim,))
    x = layers.Dense(hidden_dim, activation="relu")(x_in)
    x = layers.Dense(hidden_dim // 2, activation="relu")(x)
    out = layers.Dense(1, activation="sigmoid")(x)
    return Model(x_in, out, name="discriminator")


class VanillaCandidateGAN:
    def __init__(self, input_dim: int, latent_dim: int = 32, corr_lambda: float = 0.0):
        self.latent_dim = latent_dim
        self.corr_lambda = corr_lambda
        self.generator = build_generator(latent_dim, input_dim)
        self.discriminator = build_discriminator(input_dim)
        self.g_opt = tf.keras.optimizers.Adam(1e-3)
        self.d_opt = tf.keras.optimizers.Adam(1e-3)
        self.bce = tf.keras.losses.BinaryCrossentropy()

    @tf.function
    def train_step(self, x_real: tf.Tensor) -> Tuple[tf.Tensor, tf.Tensor]:
        batch_size = tf.shape(x_real)[0]
        z = tf.random.normal((batch_size, self.latent_dim))

        with tf.GradientTape() as d_tape, tf.GradientTape() as g_tape:
            x_fake = self.generator(z, training=True)
            d_real = self.discriminator(x_real, training=True)
            d_fake = self.discriminator(x_fake, training=True)
            d_loss = self.bce(tf.ones_like(d_real), d_real) + self.bce(tf.zeros_like(d_fake), d_fake)

            g_fake = self.discriminator(x_fake, training=True)
            g_loss_adv = self.bce(tf.ones_like(g_fake), g_fake)
            if self.corr_lambda > 0.0:
                corr_real = batch_corr(x_real)
                corr_fake = batch_corr(x_fake)
                corr_loss = tf.reduce_mean(tf.square(corr_real - corr_fake))
            else:
                corr_loss = 0.0
            g_loss = g_loss_adv + self.corr_lambda * corr_loss

        d_grads = d_tape.gradient(d_loss, self.discriminator.trainable_variables)
        g_grads = g_tape.gradient(g_loss, self.generator.trainable_variables)
        self.d_opt.apply_gradients(zip(d_grads, self.discriminator.trainable_variables))
        self.g_opt.apply_gradients(zip(g_grads, self.generator.trainable_variables))
        return d_loss, g_loss

    def fit(self, X_train: np.ndarray, epochs: int = 100, batch_size: int = 64, tag: str = "GAN") -> None:
        dataset = tf.data.Dataset.from_tensor_slices(X_train.astype(np.float32))
        dataset = dataset.shuffle(min(4096, len(X_train)), seed=SEED).batch(batch_size)

        for epoch in range(epochs):
            d_vals, g_vals = [], []
            for x_real in dataset:
                d_loss, g_loss = self.train_step(x_real)
                d_vals.append(float(d_loss.numpy()))
                g_vals.append(float(g_loss.numpy()))
            if (epoch + 1) % 20 == 0 or epoch == 0:
                print(f"[{tag}] Epoch {epoch + 1:03d}/{epochs} | D={np.mean(d_vals):.4f} | G={np.mean(g_vals):.4f}")

    def sample(self, n_samples: int) -> np.ndarray:
        z = np.random.normal(size=(n_samples, self.latent_dim)).astype(np.float32)
        return np.clip(self.generator.predict(z, verbose=0), 0.0, 1.0)


def mesh_candidate_imputation(
    X_missing: np.ndarray,
    mask: np.ndarray,
    candidates: np.ndarray,
    top_k: int = 20,
) -> np.ndarray:
    imputed = X_missing.copy()
    for i in range(len(X_missing)):
        obs = mask[i] == 1
        miss = mask[i] == 0
        if miss.sum() == 0:
            continue

        if obs.sum() == 0:
            top_idx = np.random.choice(len(candidates), size=min(top_k, len(candidates)), replace=False)
            chosen = candidates[top_idx]
            imputed[i, miss] = chosen[:, miss].mean(axis=0)
            continue

        dists = np.sum((candidates[:, obs] - X_missing[i, obs]) ** 2, axis=1)
        top_idx = np.argsort(dists)[: min(top_k, len(candidates))]
        chosen = candidates[top_idx]
        weights = 1.0 / (dists[top_idx] + 1e-6)
        weights = weights / weights.sum()
        imputed[i, miss] = np.sum(chosen[:, miss] * weights[:, None], axis=0)

    return np.clip(imputed, 0.0, 1.0)


class CorrGANStyleImputer:
    def __init__(self, input_dim: int, latent_dim: int = 32, corr_lambda: float = 5.0, pool_size: int = 4000, top_k: int = 20):
        self.gan = VanillaCandidateGAN(input_dim=input_dim, latent_dim=latent_dim, corr_lambda=corr_lambda)
        self.pool_size = pool_size
        self.top_k = top_k

    def fit(self, X_missing: np.ndarray, mask: np.ndarray, feature_names: List[str], epochs: int = 100, batch_size: int = 64) -> None:
        x_real = coarse_fill_matrix(X_missing, feature_names, sentinel=MISSING_SENTINEL)
        self.gan.fit(x_real, epochs=epochs, batch_size=batch_size, tag="CorrGANStyle")

    def transform(self, X_missing: np.ndarray, mask: np.ndarray) -> np.ndarray:
        candidates = self.gan.sample(self.pool_size)
        return mesh_candidate_imputation(X_missing, mask, candidates, top_k=self.top_k)


def preprocess_with_corrgan(
    df: pd.DataFrame,
    pollutant_cols: List[str],
    target_cols: List[str],
) -> Tuple[pd.DataFrame, np.ndarray, np.ndarray, MinMaxScaler, MinMaxScaler, Dict]:
    pollutant_df = clip_outliers(df[pollutant_cols].copy(), pollutant_cols, CLIP_LOWER_Q, CLIP_UPPER_Q)

    coarse_pollutants = pollutant_df.interpolate(limit_direction="both").ffill().bfill().fillna(0.0)
    coarse_feature_df = pd.concat(
        [coarse_pollutants.reset_index(drop=True), df[TIME_FEATURES].reset_index(drop=True)],
        axis=1,
    )

    scaler_x = MinMaxScaler()
    X_full_norm = scaler_x.fit_transform(coarse_feature_df[INPUT_FEATURES].values.astype(np.float32))

    X_missing_norm = X_full_norm.copy()
    mask = np.ones_like(X_full_norm, dtype=np.float32)

    for col in pollutant_cols:
        idx = INPUT_FEATURES.index(col)
        missing_rows = pollutant_df[col].isna().values
        X_missing_norm[missing_rows, idx] = MISSING_SENTINEL
        mask[missing_rows, idx] = 0.0

    print("[INFO] Training CorrGANStyle imputer for real missing-value completion...")
    corrgan = CorrGANStyleImputer(
        input_dim=len(INPUT_FEATURES),
        latent_dim=CORRGAN_LATENT_DIM,
        corr_lambda=CORR_LAMBDA,
        pool_size=CORRGAN_POOL_SIZE,
        top_k=CORRGAN_TOPK,
    )
    corrgan.fit(X_missing_norm, mask, INPUT_FEATURES, epochs=CORRGAN_EPOCHS, batch_size=CORRGAN_BATCH_SIZE)
    X_imp_norm = corrgan.transform(X_missing_norm, mask)
    X_imp = scaler_x.inverse_transform(X_imp_norm)

    feature_df = pd.DataFrame(X_imp, columns=INPUT_FEATURES)
    y_raw = np.clip(feature_df[target_cols].values.astype(np.float32), a_min=0.0, a_max=None)
    y_log = np.log1p(y_raw)
    scaler_y = MinMaxScaler()
    y_norm = scaler_y.fit_transform(y_log)

    preprocess_info = {
        "preprocessing": "CorrGANStyle_missing_value_imputation",
        "corrgan_epochs": CORRGAN_EPOCHS,
        "corrgan_batch_size": CORRGAN_BATCH_SIZE,
        "corrgan_pool_size": CORRGAN_POOL_SIZE,
        "corrgan_top_k": CORRGAN_TOPK,
        "input_features": INPUT_FEATURES,
        "target_cols": target_cols,
        "forecast_seq_len": FORECAST_SEQ_LEN,
        "target_transform": "log1p_then_minmax",
    }

    return feature_df, feature_df[INPUT_FEATURES].values.astype(np.float32), y_norm, scaler_x, scaler_y, preprocess_info

# =========================================================
# SEQUENCE CREATION
# =========================================================
def create_supervised_sequences(
    X_all_raw: np.ndarray,
    y_all: np.ndarray,
    seq_len: int,
    horizon: int,
    scaler_x: MinMaxScaler,
) -> Tuple[np.ndarray, np.ndarray]:
    X_all = scaler_x.transform(X_all_raw.astype(np.float32))
    X_seq, y_seq = [], []
    limit = len(X_all) - seq_len - horizon + 1
    for i in range(limit):
        X_seq.append(X_all[i:i + seq_len])
        y_seq.append(y_all[i + seq_len + horizon - 1])
    return np.asarray(X_seq, dtype=np.float32), np.asarray(y_seq, dtype=np.float32)


def split_sequences(X: np.ndarray, y: np.ndarray) -> Tuple[np.ndarray, np.ndarray, np.ndarray, np.ndarray, np.ndarray, np.ndarray]:
    n = len(X)
    n_train = int(TRAIN_RATIO * n)
    n_val = int(VAL_RATIO * n)

    X_train, y_train = X[:n_train], y[:n_train]
    X_val, y_val = X[n_train:n_train + n_val], y[n_train:n_train + n_val]
    X_test, y_test = X[n_train + n_val:], y[n_train + n_val:]
    return X_train, y_train, X_val, y_val, X_test, y_test

# =========================================================
# MODEL BUILDERS
# =========================================================
class LearnablePositionalEmbedding(layers.Layer):
    def __init__(self, seq_len: int, d_model: int, **kwargs):
        super().__init__(**kwargs)
        self.seq_len = seq_len
        self.d_model = d_model
        self.pos_emb = layers.Embedding(input_dim=seq_len, output_dim=d_model)

    def call(self, x: tf.Tensor) -> tf.Tensor:
        positions = tf.range(start=0, limit=self.seq_len, delta=1)
        return x + self.pos_emb(positions)

    def get_config(self) -> Dict:
        config = super().get_config()
        config.update({"seq_len": self.seq_len, "d_model": self.d_model})
        return config


class AttentionPooling(layers.Layer):
    def __init__(self, **kwargs):
        super().__init__(**kwargs)
        self.score_dense = layers.Dense(1)

    def call(self, x: tf.Tensor) -> tf.Tensor:
        scores = self.score_dense(x)
        weights = tf.nn.softmax(scores, axis=1)
        return tf.reduce_sum(weights * x, axis=1)


def transformer_encoder_block(
    x: tf.Tensor,
    d_model: int,
    num_heads: int,
    ff_dim: int,
    dropout: float,
) -> tf.Tensor:
    attn_input = layers.LayerNormalization(epsilon=1e-6)(x)
    attn_out = layers.MultiHeadAttention(
        num_heads=num_heads,
        key_dim=max(1, d_model // num_heads),
        dropout=dropout,
    )(attn_input, attn_input)
    attn_out = layers.Dropout(dropout)(attn_out)
    x = layers.Add()([x, attn_out])

    ff_input = layers.LayerNormalization(epsilon=1e-6)(x)
    ff = layers.Dense(ff_dim, activation="gelu")(ff_input)
    ff = layers.Dropout(dropout)(ff)
    ff = layers.Dense(d_model)(ff)
    ff = layers.Dropout(dropout)(ff)
    x = layers.Add()([x, ff])
    return x


def build_tiny_transformer(seq_len: int, num_features: int, num_outputs: int) -> Model:
    inputs = layers.Input(shape=(seq_len, num_features), name="input_seq")
    x = layers.Conv1D(CONV_FILTERS, kernel_size=5, padding="same", activation="gelu")(inputs)
    x = layers.Conv1D(CONV_FILTERS, kernel_size=3, padding="same", activation="gelu")(x)
    x = layers.Dense(D_MODEL)(x)
    x = LearnablePositionalEmbedding(seq_len, D_MODEL)(x)
    x = layers.Dropout(TRANSFORMER_DROPOUT)(x)

    for _ in range(NUM_TRANSFORMER_BLOCKS):
        x = transformer_encoder_block(x, D_MODEL, NUM_HEADS, FF_DIM, TRANSFORMER_DROPOUT)

    x_norm = layers.LayerNormalization(epsilon=1e-6)(x)
    avg_pool = layers.GlobalAveragePooling1D()(x_norm)
    max_pool = layers.GlobalMaxPooling1D()(x_norm)
    attn_pool = AttentionPooling()(x_norm)

    x = layers.Concatenate()([avg_pool, max_pool, attn_pool])
    x = layers.Dense(HEAD_DENSE_1, activation="gelu")(x)
    x = layers.Dropout(0.20)(x)
    x = layers.Dense(HEAD_DENSE_2, activation="gelu")(x)
    x = layers.Dropout(0.10)(x)
    outputs = layers.Dense(num_outputs, name="pollutant_forecast")(x)

    model = Model(inputs, outputs, name="ImprovedTinyTransformer_CorrGAN")
    model.compile(
        optimizer=tf.keras.optimizers.AdamW(learning_rate=LEARNING_RATE, weight_decay=1e-5),
        loss=tf.keras.losses.Huber(delta=1.0),
        metrics=[tf.keras.metrics.MeanAbsoluteError(name="mae")],
    )
    return model


def build_ablation_transformer(
    seq_len: int,
    num_features: int,
    num_outputs: int,
    use_conv: bool = True,
    num_blocks: int = 3,
    use_attention_pool: bool = True,
) -> Model:
    inputs = layers.Input(shape=(seq_len, num_features), name="input_seq")

    if use_conv:
        x = layers.Conv1D(CONV_FILTERS, kernel_size=5, padding="same", activation="gelu")(inputs)
        x = layers.Conv1D(CONV_FILTERS, kernel_size=3, padding="same", activation="gelu")(x)
    else:
        x = inputs

    x = layers.Dense(D_MODEL)(x)
    x = LearnablePositionalEmbedding(seq_len, D_MODEL)(x)
    x = layers.Dropout(TRANSFORMER_DROPOUT)(x)

    for _ in range(num_blocks):
        x = transformer_encoder_block(x, D_MODEL, NUM_HEADS, FF_DIM, TRANSFORMER_DROPOUT)

    x_norm = layers.LayerNormalization(epsilon=1e-6)(x)
    avg_pool = layers.GlobalAveragePooling1D()(x_norm)
    max_pool = layers.GlobalMaxPooling1D()(x_norm)

    if use_attention_pool:
        x = layers.Concatenate()([avg_pool, max_pool, AttentionPooling()(x_norm)])
    else:
        x = layers.Concatenate()([avg_pool, max_pool])

    x = layers.Dense(HEAD_DENSE_1, activation="gelu")(x)
    x = layers.Dropout(0.20)(x)
    x = layers.Dense(HEAD_DENSE_2, activation="gelu")(x)
    x = layers.Dropout(0.10)(x)
    outputs = layers.Dense(num_outputs)(x)

    model = Model(inputs, outputs, name="AblationTinyTransformer_CorrGAN")
    model.compile(
        optimizer=tf.keras.optimizers.AdamW(learning_rate=LEARNING_RATE, weight_decay=1e-5),
        loss=tf.keras.losses.Huber(delta=1.0),
        metrics=[tf.keras.metrics.MeanAbsoluteError(name="mae")],
    )
    return model


def build_cnn_baseline(seq_len: int, num_features: int, num_outputs: int) -> Model:
    inputs = layers.Input(shape=(seq_len, num_features))
    x = layers.Conv1D(64, kernel_size=5, padding="same", activation="relu")(inputs)
    x = layers.Conv1D(64, kernel_size=3, padding="same", activation="relu")(x)
    x = layers.GlobalAveragePooling1D()(x)
    x = layers.Dense(64, activation="relu")(x)
    x = layers.Dropout(0.20)(x)
    outputs = layers.Dense(num_outputs)(x)
    model = Model(inputs, outputs, name="CNN1D_Baseline")
    model.compile(
        optimizer=tf.keras.optimizers.Adam(learning_rate=LEARNING_RATE),
        loss=tf.keras.losses.Huber(delta=1.0),
        metrics=[tf.keras.metrics.MeanAbsoluteError(name="mae")],
    )
    return model


def build_lstm_baseline(seq_len: int, num_features: int, num_outputs: int) -> Model:
    inputs = layers.Input(shape=(seq_len, num_features))
    x = layers.LSTM(64, unroll=True)(inputs)
    x = layers.Dense(64, activation="relu")(x)
    x = layers.Dropout(0.20)(x)
    outputs = layers.Dense(num_outputs)(x)
    model = Model(inputs, outputs, name="LSTM_Baseline")
    model.compile(
        optimizer=tf.keras.optimizers.Adam(learning_rate=LEARNING_RATE),
        loss=tf.keras.losses.Huber(delta=1.0),
        metrics=[tf.keras.metrics.MeanAbsoluteError(name="mae")],
    )
    return model


def build_gru_baseline(seq_len: int, num_features: int, num_outputs: int) -> Model:
    inputs = layers.Input(shape=(seq_len, num_features))
    x = layers.GRU(64, unroll=True)(inputs)
    x = layers.Dense(64, activation="relu")(x)
    x = layers.Dropout(0.20)(x)
    outputs = layers.Dense(num_outputs)(x)
    model = Model(inputs, outputs, name="GRU_Baseline")
    model.compile(
        optimizer=tf.keras.optimizers.Adam(learning_rate=LEARNING_RATE),
        loss=tf.keras.losses.Huber(delta=1.0),
        metrics=[tf.keras.metrics.MeanAbsoluteError(name="mae")],
    )
    return model

# =========================================================
# METRICS
# =========================================================
def smape(y_true: np.ndarray, y_pred: np.ndarray) -> float:
    denom = np.abs(y_true) + np.abs(y_pred) + 1e-8
    return float(100.0 * np.mean(2.0 * np.abs(y_pred - y_true) / denom))


def evaluate_per_target(y_true: np.ndarray, y_pred: np.ndarray, target_cols: List[str]) -> Dict:
    results = {}
    mae_list, rmse_list, r2_list, smape_list = [], [], [], []

    for idx, col in enumerate(target_cols):
        yt = y_true[:, idx]
        yp = y_pred[:, idx]
        mae = float(mean_absolute_error(yt, yp))
        rmse = float(np.sqrt(mean_squared_error(yt, yp)))
        r2 = float(r2_score(yt, yp))
        smape_val = smape(yt, yp)

        results[col] = {
            "MAE": mae,
            "RMSE": rmse,
            "R2": r2,
            "sMAPE_percent": smape_val,
        }
        mae_list.append(mae)
        rmse_list.append(rmse)
        r2_list.append(r2)
        smape_list.append(smape_val)

    results["macro_avg"] = {
        "MAE": float(np.mean(mae_list)),
        "RMSE": float(np.mean(rmse_list)),
        "R2": float(np.mean(r2_list)),
        "sMAPE_percent": float(np.mean(smape_list)),
    }
    return results


def metrics_dict_to_dataframe(metrics_dict: Dict) -> pd.DataFrame:
    rows = []
    for name, vals in metrics_dict.items():
        row = {"target": name}
        row.update(vals)
        rows.append(row)
    return pd.DataFrame(rows)


def inverse_transform_targets(y_norm: np.ndarray, scaler_y: MinMaxScaler) -> np.ndarray:
    y_log = scaler_y.inverse_transform(y_norm)
    return np.expm1(y_log)

# =========================================================
# TRAINING HELPERS
# =========================================================
def train_keras_model(
    model: Model,
    X_train: np.ndarray,
    y_train: np.ndarray,
    X_val: np.ndarray,
    y_val: np.ndarray,
    epochs: int,
    batch_size: int,
    verbose: int = 0,
) -> Tuple[Model, Dict[str, List[float]]]:
    callbacks = [
        tf.keras.callbacks.EarlyStopping(monitor="val_loss", patience=8, restore_best_weights=True),
        tf.keras.callbacks.ReduceLROnPlateau(monitor="val_loss", factor=0.5, patience=4, min_lr=1e-5),
    ]
    history_obj = model.fit(
        X_train,
        y_train,
        validation_data=(X_val, y_val),
        epochs=epochs,
        batch_size=batch_size,
        verbose=verbose,
        callbacks=callbacks,
    )
    history = {k: [float(v) for v in vals] for k, vals in history_obj.history.items()}
    return model, history

# =========================================================
# INT8 TFLITE EXPORT AND EVAL
# =========================================================
def representative_data_gen(X_calib: np.ndarray):
    for i in range(min(200, len(X_calib))):
        yield [X_calib[i:i + 1].astype(np.float32)]


def export_tflite_int8(model: Model, X_calib: np.ndarray, save_path: str) -> None:
    converter = tf.lite.TFLiteConverter.from_keras_model(model)
    converter.optimizations = [tf.lite.Optimize.DEFAULT]
    converter.representative_dataset = lambda: representative_data_gen(X_calib)
    converter.target_spec.supported_ops = [tf.lite.OpsSet.TFLITE_BUILTINS_INT8]
    converter.inference_input_type = tf.int8
    converter.inference_output_type = tf.int8

    try:
        tflite_model = converter.convert()
    except Exception as e:
        raise RuntimeError(
            f"Pure INT8 conversion failed for model '{model.name}'. Original error: {e}"
        )

    with open(save_path, "wb") as f:
        f.write(tflite_model)


def tflite_predict_int8(tflite_path: str, X_test: np.ndarray) -> np.ndarray:
    interpreter = tf.lite.Interpreter(model_path=tflite_path)
    interpreter.allocate_tensors()

    input_details = interpreter.get_input_details()[0]
    output_details = interpreter.get_output_details()[0]

    in_scale, in_zero = input_details["quantization"]
    out_scale, out_zero = output_details["quantization"]

    preds = []
    for i in range(len(X_test)):
        x = X_test[i:i + 1].astype(np.float32)
        x_q = np.round(x / in_scale + in_zero).astype(np.int8)
        interpreter.set_tensor(input_details["index"], x_q)
        interpreter.invoke()
        y_q = interpreter.get_tensor(output_details["index"])
        y = (y_q.astype(np.float32) - out_zero) * out_scale
        preds.append(y[0])

    return np.asarray(preds, dtype=np.float32)


def save_keras_and_int8_results(
    model: Model,
    model_name: str,
    X_train: np.ndarray,
    X_test: np.ndarray,
    y_test: np.ndarray,
    scaler_y: MinMaxScaler,
    target_cols: List[str],
    save_dir: str,
) -> Tuple[Dict, Optional[Dict]]:
    os.makedirs(save_dir, exist_ok=True)

    keras_path = os.path.join(save_dir, f"{model_name}.keras")
    int8_path = os.path.join(save_dir, f"{model_name}_int8.tflite")
    model.save(keras_path)

    y_true = inverse_transform_targets(y_test, scaler_y)

    y_pred_keras_norm = model.predict(X_test, verbose=0)
    y_pred_keras = inverse_transform_targets(y_pred_keras_norm, scaler_y)
    keras_metrics = evaluate_per_target(y_true, y_pred_keras, target_cols)

    with open(os.path.join(save_dir, f"{model_name}_keras_metrics.json"), "w") as f:
        json.dump(keras_metrics, f, indent=2)
    metrics_dict_to_dataframe(keras_metrics).to_csv(os.path.join(save_dir, f"{model_name}_keras_metrics.csv"), index=False)

    int8_metrics = None
    try:
        export_tflite_int8(model, X_train[: min(200, len(X_train))], int8_path)
        y_pred_tflite_norm = tflite_predict_int8(int8_path, X_test)
        y_pred_tflite = inverse_transform_targets(y_pred_tflite_norm, scaler_y)
        int8_metrics = evaluate_per_target(y_true, y_pred_tflite, target_cols)

        with open(os.path.join(save_dir, f"{model_name}_int8_metrics.json"), "w") as f:
            json.dump(int8_metrics, f, indent=2)
        metrics_dict_to_dataframe(int8_metrics).to_csv(os.path.join(save_dir, f"{model_name}_int8_metrics.csv"), index=False)
    except Exception as e:
        error_info = {"model_name": model_name, "error": str(e)}
        with open(os.path.join(save_dir, f"{model_name}_int8_error.json"), "w") as f:
            json.dump(error_info, f, indent=2)
        print(f"\n[WARNING] INT8 export failed for {model_name}: {e}")

    print(f"\n===== {model_name} FP32 METRICS =====")
    print(json.dumps(keras_metrics, indent=2))
    if int8_metrics is not None:
        print(f"\n===== {model_name} INT8 METRICS =====")
        print(json.dumps(int8_metrics, indent=2))

    return keras_metrics, int8_metrics

# =========================================================
# SAVE / PLOT HELPERS
# =========================================================
def save_scaler_info(scaler_x: MinMaxScaler, scaler_y: MinMaxScaler, preprocess_info: Dict) -> None:
    info = {
        **preprocess_info,
        "scaler_x_data_min": scaler_x.data_min_.tolist(),
        "scaler_x_data_max": scaler_x.data_max_.tolist(),
        "scaler_x_scale": scaler_x.scale_.tolist(),
        "scaler_x_min": scaler_x.min_.tolist(),
        "scaler_y_data_min": scaler_y.data_min_.tolist(),
        "scaler_y_data_max": scaler_y.data_max_.tolist(),
        "scaler_y_scale": scaler_y.scale_.tolist(),
        "scaler_y_min": scaler_y.min_.tolist(),
    }
    with open(os.path.join(OUT_DIR, "scaler_info.json"), "w") as f:
        json.dump(info, f, indent=2)


def save_history_plot(history: Dict[str, List[float]], save_path: str, title: str) -> None:
    plt.figure(figsize=(8, 5))
    if "loss" in history:
        plt.plot(history["loss"], label="Train Loss")
    if "val_loss" in history:
        plt.plot(history["val_loss"], label="Val Loss")
    plt.xlabel("Epoch")
    plt.ylabel("Loss")
    plt.title(title)
    plt.legend()
    plt.tight_layout()
    plt.savefig(save_path, dpi=300)
    plt.close()


def plot_results_bar(df_results: pd.DataFrame, save_dir: str, prefix: str) -> None:
    for metric in ["MAE", "RMSE", "R2", "sMAPE_percent"]:
        plt.figure(figsize=(10, 5))
        plt.bar(df_results["variant"], df_results[metric])
        plt.xticks(rotation=20, ha="right")
        plt.ylabel(metric)
        plt.title(f"{prefix} - {metric}")
        plt.tight_layout()
        plt.savefig(os.path.join(save_dir, f"{prefix.lower().replace(' ', '_')}_{metric}.png"), dpi=300)
        plt.close()

# =========================================================
# BASELINE COMPARISON WITH INT8
# =========================================================
def evaluate_linear_regression_baseline(
    X_train: np.ndarray,
    y_train: np.ndarray,
    X_test: np.ndarray,
    y_test: np.ndarray,
    scaler_y: MinMaxScaler,
    target_cols: List[str],
    save_dir: str,
) -> Dict:
    X_train_flat = X_train.reshape(X_train.shape[0], -1)
    X_test_flat = X_test.reshape(X_test.shape[0], -1)

    model = MultiOutputRegressor(LinearRegression())
    model.fit(X_train_flat, y_train)
    y_pred_norm = model.predict(X_test_flat)

    y_true = inverse_transform_targets(y_test, scaler_y)
    y_pred = inverse_transform_targets(y_pred_norm, scaler_y)
    metrics = evaluate_per_target(y_true, y_pred, target_cols)

    with open(os.path.join(save_dir, "linear_regression_metrics.json"), "w") as f:
        json.dump(metrics, f, indent=2)

    print("\n===== LinearRegression FP32-ONLY METRICS =====")
    print(json.dumps(metrics, indent=2))
    return metrics


def run_baseline_comparison(
    target_cols: List[str],
    scaler_y: MinMaxScaler,
    X_train: np.ndarray,
    y_train: np.ndarray,
    X_val: np.ndarray,
    y_val: np.ndarray,
    X_test: np.ndarray,
    y_test: np.ndarray,
    proposed_fp32_metrics: Dict,
    proposed_int8_metrics: Optional[Dict],
) -> None:
    print("\n[INFO] Running baseline comparison with INT8 export...")
    baseline_dir = os.path.join(OUT_DIR, "baseline_comparison")
    int8_dir = os.path.join(baseline_dir, "int8_models")
    os.makedirs(baseline_dir, exist_ok=True)
    os.makedirs(int8_dir, exist_ok=True)

    results_fp32 = []
    results_int8 = []

    linear_metrics = evaluate_linear_regression_baseline(X_train, y_train, X_test, y_test, scaler_y, target_cols, baseline_dir)
    results_fp32.append({"variant": "LinearRegression", "epochs_ran": 0, **linear_metrics["macro_avg"]})

    keras_baselines = [
        ("CNN1D", build_cnn_baseline),
        ("LSTM", build_lstm_baseline),
        ("GRU", build_gru_baseline),
    ]

    for name, builder in keras_baselines:
        tf.keras.backend.clear_session()
        set_global_determinism(SEED)
        model = builder(X_train.shape[1], X_train.shape[2], len(target_cols))
        model, history = train_keras_model(model, X_train, y_train, X_val, y_val, BASELINE_EPOCHS, BATCH_SIZE, verbose=0)

        with open(os.path.join(baseline_dir, f"{name.lower()}_history.json"), "w") as f:
            json.dump(history, f, indent=2)

        fp32_metrics, int8_metrics = save_keras_and_int8_results(
            model=model,
            model_name=name.lower(),
            X_train=X_train,
            X_test=X_test,
            y_test=y_test,
            scaler_y=scaler_y,
            target_cols=target_cols,
            save_dir=int8_dir,
        )

        results_fp32.append({"variant": name, "epochs_ran": len(history["loss"]), **fp32_metrics["macro_avg"]})
        if int8_metrics is not None:
            results_int8.append({"variant": f"{name}_INT8", "epochs_ran": len(history["loss"]), **int8_metrics["macro_avg"]})

    results_fp32.append({"variant": "Proposed_ImprovedTinyTransformer", "epochs_ran": -1, **proposed_fp32_metrics["macro_avg"]})
    if proposed_int8_metrics is not None:
        results_int8.append({"variant": "Proposed_ImprovedTinyTransformer_INT8", "epochs_ran": -1, **proposed_int8_metrics["macro_avg"]})

    df_fp32 = pd.DataFrame(results_fp32).sort_values(by="RMSE")
    df_fp32.to_csv(os.path.join(baseline_dir, "baseline_results_fp32.csv"), index=False)
    plot_results_bar(df_fp32, baseline_dir, prefix="Baseline Comparison FP32")

    print("\n===== BASELINE COMPARISON FP32 RESULTS =====")
    print(df_fp32.to_string(index=False))

    if results_int8:
        df_int8 = pd.DataFrame(results_int8).sort_values(by="RMSE")
        df_int8.to_csv(os.path.join(baseline_dir, "baseline_results_int8.csv"), index=False)
        plot_results_bar(df_int8, baseline_dir, prefix="Baseline Comparison INT8")
        print("\n===== BASELINE COMPARISON INT8 RESULTS =====")
        print(df_int8.to_string(index=False))

# =========================================================
# ABLATION STUDY WITH INT8
# =========================================================
def run_ablation_study(
    X_train: np.ndarray,
    y_train: np.ndarray,
    X_val: np.ndarray,
    y_val: np.ndarray,
    X_test: np.ndarray,
    y_test: np.ndarray,
    scaler_y: MinMaxScaler,
    target_cols: List[str],
) -> None:
    print("\n[INFO] Running tiny transformer ablation study with INT8 export on CorrGAN-imputed data...")
    ablation_dir = os.path.join(OUT_DIR, "ablation_study")
    int8_dir = os.path.join(ablation_dir, "int8_models")
    os.makedirs(ablation_dir, exist_ok=True)
    os.makedirs(int8_dir, exist_ok=True)

    variants = [
        {"name": "full_model_corrgan", "label": "Full_Model_CorrGAN", "builder_kwargs": {"use_conv": True, "num_blocks": 3, "use_attention_pool": True}},
        {"name": "no_conv_frontend", "label": "No_Conv_Frontend", "builder_kwargs": {"use_conv": False, "num_blocks": 3, "use_attention_pool": True}},
        {"name": "one_transformer_block", "label": "One_Transformer_Block", "builder_kwargs": {"use_conv": True, "num_blocks": 1, "use_attention_pool": True}},
        {"name": "no_attention_pooling", "label": "No_Attention_Pooling", "builder_kwargs": {"use_conv": True, "num_blocks": 3, "use_attention_pool": False}},
    ]

    rows_fp32 = []
    rows_int8 = []
    for variant in variants:
        label = variant["label"]
        name = variant["name"]
        print(f"[ABLATION] Training: {label}")

        tf.keras.backend.clear_session()
        set_global_determinism(SEED)
        model = build_ablation_transformer(
            seq_len=FORECAST_SEQ_LEN,
            num_features=X_train.shape[-1],
            num_outputs=len(target_cols),
            **variant["builder_kwargs"],
        )
        model, history = train_keras_model(model, X_train, y_train, X_val, y_val, ABLATION_EPOCHS, BATCH_SIZE, verbose=0)

        with open(os.path.join(ablation_dir, f"{name}_history.json"), "w") as f:
            json.dump(history, f, indent=2)

        fp32_metrics, int8_metrics = save_keras_and_int8_results(
            model=model,
            model_name=name,
            X_train=X_train,
            X_test=X_test,
            y_test=y_test,
            scaler_y=scaler_y,
            target_cols=target_cols,
            save_dir=int8_dir,
        )

        rows_fp32.append({"variant": label, "epochs_ran": len(history["loss"]), **fp32_metrics["macro_avg"]})
        if int8_metrics is not None:
            rows_int8.append({"variant": f"{label}_INT8", "epochs_ran": len(history["loss"]), **int8_metrics["macro_avg"]})

    df_fp32 = pd.DataFrame(rows_fp32).sort_values(by="RMSE")
    df_fp32.to_csv(os.path.join(ablation_dir, "ablation_results_fp32.csv"), index=False)
    plot_results_bar(df_fp32, ablation_dir, prefix="Ablation Study FP32")

    print("\n===== ABLATION RESULTS FP32 =====")
    print(df_fp32.to_string(index=False))

    if rows_int8:
        df_int8 = pd.DataFrame(rows_int8).sort_values(by="RMSE")
        df_int8.to_csv(os.path.join(ablation_dir, "ablation_results_int8.csv"), index=False)
        plot_results_bar(df_int8, ablation_dir, prefix="Ablation Study INT8")
        print("\n===== ABLATION RESULTS INT8 =====")
        print(df_int8.to_string(index=False))

# =========================================================
# MAIN
# =========================================================
def main() -> None:
    set_global_determinism(SEED)

    print("[INFO] Loading dataset...")
    df = load_data(CSV_PATH)
    validate_required_columns(df)
    df = add_time_features(df)

    print("\n[INFO] CorrGANStyle was the best imputation method in your benchmark.")
    print("[INFO] Using CorrGANStyle for missing-value completion before forecasting.")

    feature_df, X_raw, y_norm, scaler_x, scaler_y, preprocess_info = preprocess_with_corrgan(
        df=df,
        pollutant_cols=POLLUTANT_INPUT_COLS,
        target_cols=TARGET_COLS,
    )

    feature_df.to_csv(os.path.join(OUT_DIR, "corrgan_imputed_feature_dataset.csv"), index=False)
    save_scaler_info(scaler_x, scaler_y, preprocess_info)

    print("\n[INFO] Creating supervised sequences for forecasting...")
    X, y = create_supervised_sequences(
        X_all_raw=X_raw,
        y_all=y_norm,
        seq_len=FORECAST_SEQ_LEN,
        horizon=TARGET_HORIZON,
        scaler_x=scaler_x,
    )
    print(f"[INFO] Supervised shapes: X={X.shape}, y={y.shape}")

    X_train, y_train, X_val, y_val, X_test, y_test = split_sequences(X, y)
    print(f"[INFO] Train: {X_train.shape}, Val: {X_val.shape}, Test: {X_test.shape}")

    print("\n[INFO] Training proposed improved tiny transformer...")
    model = build_tiny_transformer(
        seq_len=FORECAST_SEQ_LEN,
        num_features=X_train.shape[-1],
        num_outputs=len(TARGET_COLS),
    )
    model.summary()

    callbacks = [
        tf.keras.callbacks.EarlyStopping(monitor="val_loss", patience=15, restore_best_weights=True),
        tf.keras.callbacks.ReduceLROnPlateau(monitor="val_loss", factor=0.5, patience=7, min_lr=1e-5),
        tf.keras.callbacks.ModelCheckpoint(
            filepath=os.path.join(OUT_DIR, "best_tiny_transformer_corrgan.keras"),
            monitor="val_loss",
            save_best_only=True,
        ),
    ]

    history_obj = model.fit(
        X_train,
        y_train,
        validation_data=(X_val, y_val),
        epochs=MODEL_EPOCHS,
        batch_size=BATCH_SIZE,
        callbacks=callbacks,
        verbose=1,
    )

    history = {k: [float(v) for v in vals] for k, vals in history_obj.history.items()}
    with open(os.path.join(OUT_DIR, "forecast_history.json"), "w") as f:
        json.dump(history, f, indent=2)
    save_history_plot(history, os.path.join(OUT_DIR, "forecast_training_curve.png"), "Improved Tiny Transformer on CorrGAN-Imputed Data")

    proposed_dir = os.path.join(OUT_DIR, "proposed_model")
    proposed_fp32_metrics, proposed_int8_metrics = save_keras_and_int8_results(
        model=model,
        model_name="proposed_improved_tiny_transformer",
        X_train=X_train,
        X_test=X_test,
        y_test=y_test,
        scaler_y=scaler_y,
        target_cols=TARGET_COLS,
        save_dir=proposed_dir,
    )

    run_baseline_comparison(
        target_cols=TARGET_COLS,
        scaler_y=scaler_y,
        X_train=X_train,
        y_train=y_train,
        X_val=X_val,
        y_val=y_val,
        X_test=X_test,
        y_test=y_test,
        proposed_fp32_metrics=proposed_fp32_metrics,
        proposed_int8_metrics=proposed_int8_metrics,
    )

    run_ablation_study(
        X_train=X_train,
        y_train=y_train,
        X_val=X_val,
        y_val=y_val,
        X_test=X_test,
        y_test=y_test,
        scaler_y=scaler_y,
        target_cols=TARGET_COLS,
    )

    print(f"\n[INFO] All outputs saved in: {OUT_DIR}")


if __name__ == "__main__":
    main()